#!/usr/bin/env python3
"""Run the LO h -> gamma gamma campaign.

The sample table below is intentionally plain Python.  Edit it to add, remove,
or reweight samples without having to chase shell quoting.
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_HERWIG_PREFIX = Path.home() / "Projects/Herwig/Herwig-REAL-stable-gcc-full"
DEFAULT_LINUX_HERWIG_MODULE = "herwig/stable"
DEFAULT_DARWIN_HERWIG_MODULE = "herwig/730"
LO_PDF_NAME = "NNPDF40_lo_as_01180"
LO_PDF_LHAID = 331900
NLO_PDF_NAME = "NNPDF40_nlo_as_01180_qed"
NLO_PDF_LHAID = 335900
NNLO_PDF_NAME = "NNPDF40_nnlo_as_01180_qed"
NNLO_PDF_LHAID = 336100
YR4_BR_H_TO_GAMMAGAMMA = 2.27e-3
SIGNAL_GGH_K_FACTOR = 2.0
SIGNAL_GGH_TO_GAMMAGAMMA_WEIGHT = SIGNAL_GGH_K_FACTOR * YR4_BR_H_TO_GAMMAGAMMA
MG5_PDF_LABEL_SYNC_MARKER = "# gamma-gamma campaign PDF label sync"


@dataclass(frozen=True)
class Sample:
    name: str
    category: str
    model: str
    process: str
    madspin_decay: str
    weight_scale: float


# name | category | model | process | madspin_decay | weight_scale
SAMPLES: list[Sample] = [
    # MadSpin decays every generated Higgs to photons, so the LHE cross section
    # is the inclusive LO gg -> h rate.  Apply K(ggH) * BR(H -> gamma gamma)
    # here to normalize the signal to sigma(ggH) * BR * efficiency.
    Sample(
        "signal_gg_h_aa",
        "Signal",
        "loop_sm_haa",
        "g g > h [noborn=QCD]",
        "h > a a",
        SIGNAL_GGH_TO_GAMMAGAMMA_WEIGHT,
    ),
    Sample("bkg_prompt_aa", "Backgrounds", "sm", "p p > a a", "", 1.0),
    # Loop-induced prompt continuum.  This is separate from the tree-level
    # q qbar -> gamma gamma component generated by "p p > a a" in the SM.
    # Sample("bkg_loop_gg_aa", "Backgrounds", "loop_sm", "g g > a a [noborn=QCD]", "", 1.0),
    # Reducible fake-background starting points.  Set the weight scale to the
    # desired total fake cross-section factor before enabling them.
    # Sample("bkg_gamma_j", "Backgrounds", "sm", "p p > a j", "", 1.0),
    # Sample("bkg_jj", "Backgrounds", "sm", "p p > j j", "", 1.0),
    # Sample("bkg_ee", "Backgrounds", "sm", "p p > e+ e-", "", 1.0),
]


@dataclass
class Config:
    nevents: int
    ebeam: float
    mg5_dir: Path
    mg5_python: str | None
    herwig: str
    herwig_env: Path | None
    herwig_module: str | None
    herwig_pdf: str
    collier_library: Path | None
    run_tag: str
    run_samples: str
    dry_run: bool
    nb_core: int
    seed_base: int
    gen_photon_pt_min: float
    gen_photon_eta_max: float
    gen_jet_pt_min: float
    gen_jet_eta_max: float
    gen_lepton_pt_min: float
    gen_lepton_eta_max: float
    gen_draa_min: float
    gen_draj_min: float
    gen_dral_min: float
    gen_drjj_min: float
    gen_drll_min: float

    @property
    def template_in(self) -> Path:
        return SCRIPT_DIR / "HW-template.in"

    @property
    def analysis_code_dir(self) -> Path:
        return SCRIPT_DIR / "LOAnalysis" / "Code"

    @property
    def analysis_exe(self) -> Path:
        return self.analysis_code_dir / "HwSimPostAnalysis_gammagamma"


def env_text(name: str, default: str) -> str:
    return os.environ.get(name, default)


def env_int(name: str, default: int) -> int:
    return int(os.environ.get(name, str(default)))


def env_float(name: str, default: float) -> float:
    return float(os.environ.get(name, str(default)))


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def maybe_path(value: str | None) -> Path | None:
    if not value:
        return None
    return Path(value).expanduser()


def guess_default_herwig_env() -> Path | None:
    default = maybe_path(os.environ.get("DEFAULT_HERWIG_ENV"))
    if default and default.exists():
        return default
    candidate = DEFAULT_HERWIG_PREFIX / "bin" / "activate"
    return candidate if candidate.exists() else None


def clean_optional_text(value: str | None) -> str | None:
    if value is None:
        return None
    value = value.strip()
    return value or None


def guess_collier_library(herwig_env: Path | None) -> Path | None:
    explicit = os.environ.get("COLLIER_LIBRARY") or os.environ.get("COLLIER_DYLIB")
    if explicit:
        return Path(explicit).expanduser()

    prefix = DEFAULT_HERWIG_PREFIX
    if herwig_env and herwig_env.name == "activate":
        prefix = herwig_env.parent.parent

    system = platform.system()
    if system == "Darwin":
        fixed_candidates = [
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.2.dylib",
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.dylib",
        ]
        glob_pattern = "libcollier*.dylib"
    else:
        fixed_candidates = [
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.so",
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.so.2",
        ]
        glob_pattern = "libcollier.so*"

    for candidate in fixed_candidates:
        if candidate.exists():
            return candidate

    opt_dir = prefix / "opt"
    if opt_dir.exists():
        for candidate in sorted(opt_dir.glob(f"OpenLoops-*/lib/{glob_pattern}")):
            if candidate.exists():
                return candidate
    return None


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nevents", type=int, default=env_int("NEVENTS", 10000))
    parser.add_argument("--ebeam", type=float, default=env_float("EBEAM", 20000.0))
    parser.add_argument("--mg5-dir", type=Path, default=Path(env_text("MG5_DIR", str(REPO_ROOT / "MG5_aMC_v3_5_15"))))
    parser.add_argument(
        "--mg5-python",
        default=clean_optional_text(os.environ.get("MG5_PYTHON")),
        help="optional Python executable used to run MG5, e.g. python3.11 on systems whose default python3 is too old",
    )
    parser.add_argument("--herwig", default=env_text("HERWIG", "Herwig"))
    parser.add_argument("--herwig-env", type=Path, default=maybe_path(os.environ.get("HERWIG_ENV")))
    parser.add_argument(
        "--herwig-module",
        default=os.environ.get("HERWIG_MODULE"),
        help=(
            "environment module to load before Herwig/HwSim commands, e.g. herwig/730 "
            "on the laptop or herwig/stable on timur"
        ),
    )
    parser.add_argument(
        "--no-herwig-module",
        action="store_true",
        default=env_bool("NO_HERWIG_MODULE", False),
        help="disable the automatic platform Herwig module default",
    )
    parser.add_argument("--herwig-pdf", default=env_text("HERWIG_PDF", LO_PDF_NAME))
    parser.add_argument("--collier-library", type=Path, default=None)
    parser.add_argument("--run-tag", default=env_text("RUN_TAG", "run_01"))
    parser.add_argument("--run-samples", default=env_text("RUN_SAMPLES", "signal_gg_h_aa,bkg_prompt_aa"))
    parser.add_argument("--dry-run", action="store_true", default=env_bool("DRY_RUN", False))
    parser.add_argument("--nb-core", type=int, default=env_int("NB_CORE", 1))
    parser.add_argument("--seed-base", type=int, default=env_int("SEED_BASE", 31122002))
    parser.add_argument("--gen-photon-pt-min", type=float, default=env_float("GEN_PHOTON_PT_MIN", 10.0))
    parser.add_argument("--gen-photon-eta-max", type=float, default=env_float("GEN_PHOTON_ETA_MAX", 6.0))
    parser.add_argument("--gen-jet-pt-min", type=float, default=env_float("GEN_JET_PT_MIN", 10.0))
    parser.add_argument("--gen-jet-eta-max", type=float, default=env_float("GEN_JET_ETA_MAX", 6.0))
    parser.add_argument("--gen-lepton-pt-min", type=float, default=env_float("GEN_LEPTON_PT_MIN", 10.0))
    parser.add_argument("--gen-lepton-eta-max", type=float, default=env_float("GEN_LEPTON_ETA_MAX", 6.0))
    parser.add_argument("--gen-draa-min", type=float, default=env_float("GEN_DRAA_MIN", 0.4))
    parser.add_argument("--gen-draj-min", type=float, default=env_float("GEN_DRAJ_MIN", 0.4))
    parser.add_argument("--gen-dral-min", type=float, default=env_float("GEN_DRAL_MIN", 0.4))
    parser.add_argument("--gen-drjj-min", type=float, default=env_float("GEN_DRJJ_MIN", 0.4))
    parser.add_argument("--gen-drll-min", type=float, default=env_float("GEN_DRLL_MIN", 0.0))
    return parser


def parse_config(argv: Sequence[str]) -> Config:
    args = build_parser().parse_args(argv)
    explicit_herwig_env = args.herwig_env.expanduser() if args.herwig_env else None
    herwig_module = clean_optional_text(args.herwig_module)
    if herwig_module is None and explicit_herwig_env is None and not args.no_herwig_module:
        system = platform.system()
        if system == "Linux":
            herwig_module = DEFAULT_LINUX_HERWIG_MODULE
        elif system == "Darwin":
            herwig_module = DEFAULT_DARWIN_HERWIG_MODULE
    if args.no_herwig_module:
        herwig_module = None
    herwig_env = explicit_herwig_env
    if herwig_env is None and herwig_module is None:
        herwig_env = guess_default_herwig_env()

    collier_library = args.collier_library or guess_collier_library(herwig_env)
    return Config(
        nevents=args.nevents,
        ebeam=args.ebeam,
        mg5_dir=args.mg5_dir.expanduser(),
        mg5_python=clean_optional_text(args.mg5_python),
        herwig=args.herwig,
        herwig_env=herwig_env,
        herwig_module=herwig_module,
        herwig_pdf=args.herwig_pdf,
        collier_library=collier_library.expanduser() if collier_library else None,
        run_tag=args.run_tag,
        run_samples=args.run_samples,
        dry_run=args.dry_run,
        nb_core=args.nb_core,
        seed_base=args.seed_base,
        gen_photon_pt_min=args.gen_photon_pt_min,
        gen_photon_eta_max=args.gen_photon_eta_max,
        gen_jet_pt_min=args.gen_jet_pt_min,
        gen_jet_eta_max=args.gen_jet_eta_max,
        gen_lepton_pt_min=args.gen_lepton_pt_min,
        gen_lepton_eta_max=args.gen_lepton_eta_max,
        gen_draa_min=args.gen_draa_min,
        gen_draj_min=args.gen_draj_min,
        gen_dral_min=args.gen_dral_min,
        gen_drjj_min=args.gen_drjj_min,
        gen_drll_min=args.gen_drll_min,
    )


def q(value: object) -> str:
    return shlex.quote(str(value))


def clean_shell_env(env: dict[str, str] | None = None) -> dict[str, str]:
    shell_env = dict(os.environ if env is None else env)
    for key in list(shell_env):
        if key.startswith("BASH_FUNC_") and key.endswith("%%"):
            shell_env.pop(key, None)
    return shell_env


def format_command(args: Sequence[object]) -> str:
    return " ".join(q(arg) for arg in args)


def mg5_command(cfg: Config, *extra_args: object) -> list[object]:
    launcher = cfg.mg5_dir / "bin" / "mg5_aMC"
    if cfg.mg5_python:
        return [cfg.mg5_python, launcher, *extra_args]
    return [launcher, *extra_args]


def log(message: str) -> None:
    print(f"\n==> {message}")


def die(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def ensure_dir(path: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ mkdir -p {q(path)}")
    else:
        path.mkdir(parents=True, exist_ok=True)


def run(args: Sequence[object], cfg: Config, cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    prefix = f"+ cd {q(cwd)} && " if cwd else "+ "
    print(prefix + format_command(args))
    if cfg.dry_run:
        return
    subprocess.run([str(arg) for arg in args], cwd=cwd, env=env, check=True)


def run_shell(command: str, cfg: Config, cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    run(["bash", "-lc", command], cfg, cwd=cwd, env=clean_shell_env(env))


def module_setup_snippet() -> str:
    return (
        "if ! type module >/dev/null 2>&1; then "
        "for module_init in "
        "/opt/homebrew/opt/modules/init/bash "
        "/etc/profile.d/modules.sh "
        "/usr/share/Modules/init/bash "
        "/usr/share/lmod/lmod/init/bash; do "
        "[ -r \"$module_init\" ] && source \"$module_init\" && break; "
        "done; "
        "fi"
    )


def runtime_setup_commands(cfg: Config) -> list[str]:
    commands = ["set -e"]
    if cfg.herwig_env:
        commands.append(f"source {q(cfg.herwig_env)}")
    if cfg.herwig_module:
        commands.append(module_setup_snippet())
        commands.append(f"module load {q(cfg.herwig_module)}")
    return commands


def run_runtime_command(
    args: Sequence[object],
    cfg: Config,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
) -> None:
    if not cfg.herwig_env and not cfg.herwig_module:
        run(args, cfg, cwd=cwd, env=env)
        return
    command = "; ".join([*runtime_setup_commands(cfg), format_command(args)])
    run_shell(command, cfg, cwd=cwd, env=env)


def require_inputs(cfg: Config) -> None:
    if not cfg.template_in.exists():
        die(f"missing Herwig template: {cfg.template_in}")
    if not (cfg.mg5_dir / "bin" / "mg5_aMC").exists():
        die(f"missing MG5 executable: {cfg.mg5_dir / 'bin' / 'mg5_aMC'}")
    if cfg.mg5_python and shutil.which(cfg.mg5_python) is None:
        die(f"MG5 Python executable not found on PATH: {cfg.mg5_python}")
    if cfg.herwig_env and not cfg.herwig_env.exists():
        die(f"missing Herwig activation script: {cfg.herwig_env}")
    if not cfg.herwig_env and not cfg.herwig_module and shutil.which(cfg.herwig) is None:
        die(f"Herwig not found on PATH; set --herwig-env, --herwig-module, or --herwig")
    if cfg.collier_library and not cfg.collier_library.exists():
        die(f"missing COLLIER/OpenLoops library: {cfg.collier_library}")


def sample_requested(sample: Sample, cfg: Config) -> bool:
    if cfg.run_samples == "all":
        return True
    requested = {part.strip() for part in cfg.run_samples.split(",") if part.strip()}
    return sample.name in requested


def write_mg5_process_card(card: Path, sample: Sample, output_dir: Path, cfg: Config) -> None:
    text = f"""import model {sample.model}
define p = g u c d s u~ c~ d~ s~
define j = g u c d s u~ c~ d~ s~
define l+ = e+ mu+
define l- = e- mu-
define vl = ve vm vt
define vl~ = ve~ vm~ vt~
generate {sample.process}
output {output_dir} -f
"""
    if cfg.dry_run:
        print(f"+ write MG5 process card {card}")
        print(text, end="")
    else:
        card.write_text(text)


def write_madspin_card(card: Path, decay: str, cfg: Config) -> None:
    text = f"""set spinmode none
decay {decay}
launch
"""
    if cfg.dry_run:
        print(f"+ write MadSpin card {card}")
        print(text, end="")
    else:
        card.write_text(text)


def patch_run_card(card: Path, seed: int, cfg: Config) -> None:
    updates = {
        "nevents": str(cfg.nevents),
        "ebeam1": str(cfg.ebeam),
        "ebeam2": str(cfg.ebeam),
        "iseed": str(seed),
        "pdlabel": "lhapdf",
        "lhaid": str(LO_PDF_LHAID),
        "pta": str(cfg.gen_photon_pt_min),
        "etaa": str(cfg.gen_photon_eta_max),
        "ptj": str(cfg.gen_jet_pt_min),
        "etaj": str(cfg.gen_jet_eta_max),
        "ptl": str(cfg.gen_lepton_pt_min),
        "etal": str(cfg.gen_lepton_eta_max),
        "draa": str(cfg.gen_draa_min),
        "draj": str(cfg.gen_draj_min),
        "dral": str(cfg.gen_dral_min),
        "drjj": str(cfg.gen_drjj_min),
        "drll": str(cfg.gen_drll_min),
    }
    if cfg.dry_run:
        print(f"+ patch run card {card}")
        print(
            "nevents={nevents}, ebeam1={ebeam1}, ebeam2={ebeam2}, iseed={iseed}".format(**updates)
        )
        print("pdlabel={pdlabel}, lhaid={lhaid}".format(**updates))
        print(
            "pta={pta}, etaa={etaa}, ptj={ptj}, etaj={etaj}, "
            "ptl={ptl}, etal={etal}, draa={draa}, draj={draj}, dral={dral}, "
            "drjj={drjj}, drll={drll}".format(**updates)
        )
        return

    pattern = re.compile(r"^(\s*)([^=]+?)(\s*=\s*)([A-Za-z0-9_]+)(.*)$")
    output_lines: list[str] = []
    for line in card.read_text().splitlines(keepends=True):
        match = pattern.match(line)
        if match:
            indent, _value, sep, key, tail = match.groups()
            if key in updates:
                line = f"{indent}{updates[key]:>12}{sep}{key}{tail}\n"
        output_lines.append(line)
    card.write_text("".join(output_lines))


def rewrite_run_card_include(text: str) -> str:
    updates = {
        "PDLABEL": "'lhapdf'",
        "PDSUBLABEL(1)": "'lhapdf'",
        "PDSUBLABEL(2)": "'lhapdf'",
        "LHAID": str(LO_PDF_LHAID),
    }
    output_lines: list[str] = []
    for line in text.splitlines(keepends=True):
        for key, value in updates.items():
            pattern = re.compile(rf"^(\s*){re.escape(key)}(\s*=\s*).*$")
            if pattern.match(line.rstrip("\n")):
                newline = "\n" if line.endswith("\n") else ""
                line = pattern.sub(lambda match: f"{match.group(1)}{key}{match.group(2)}{value}", line.rstrip("\n")) + newline
                break
        output_lines.append(line)
    return "".join(output_lines)


def generate_run_card_include(process_dir: Path, cfg: Config) -> None:
    source_dir = process_dir / "Source"
    include_path = source_dir / "run_card.inc"
    if cfg.dry_run:
        print(f"+ make -C {source_dir} run_card.inc")
        return
    run(["make", "-C", source_dir, "run_card.inc"], cfg)
    if not include_path.exists():
        die(f"MG5 did not generate run card include: {include_path}")


def patch_run_card_include(process_dir: Path, cfg: Config) -> None:
    include_path = process_dir / "Source" / "run_card.inc"
    setrun_object = process_dir / "Source" / "setrun.o"
    if cfg.dry_run:
        print(f"+ patch generated MG5 include {include_path}")
        print(f"+ remove stale compiled setrun object {setrun_object} if present")
        return
    if setrun_object.exists():
        setrun_object.unlink()
    if not include_path.exists():
        return
    updated = rewrite_run_card_include(include_path.read_text())
    include_path.write_text(updated)


def patch_mg5_pdf_label_sync(process_dir: Path, cfg: Config) -> None:
    interface = process_dir / "bin" / "internal" / "madevent_interface.py"
    if cfg.dry_run:
        print(f"+ patch MG5 PDF label sync {interface}")
        return
    if not interface.exists():
        die(f"missing MG5 generated interface: {interface}")

    text = interface.read_text()
    if MG5_PDF_LABEL_SYNC_MARKER in text:
        return

    needle = "        # set  lhapdf.\n"
    if needle not in text:
        die(f"could not locate MG5 LHAPDF setup block in {interface}")

    block = (
        f"        {MG5_PDF_LABEL_SYNC_MARKER}\n"
        "        if self.run_card['pdlabel1'] == \"lhapdf\" or self.run_card['pdlabel2'] == \"lhapdf\":\n"
        "            self.run_card['pdlabel'] = \"lhapdf\"\n"
    )
    interface.write_text(text.replace(needle, needle + block, 1))


def patch_mg5_pdf_defaults(process_dir: Path, cfg: Config) -> None:
    banner = process_dir / "bin" / "internal" / "banner.py"
    if cfg.dry_run:
        print(f"+ patch MG5 PDF hidden defaults {banner}")
        return
    if not banner.exists():
        die(f"missing MG5 generated banner helper: {banner}")

    replacements = {
        'self.add_param("pdlabel", "nn23lo1", hidden=True, allowed=valid_pdf)': (
            'self.add_param("pdlabel", "lhapdf", hidden=True, allowed=valid_pdf)'
        ),
        'self.add_param("pdlabel1", "nn23lo1", hidden=True, allowed=valid_pdf, fortran_name="pdsublabel(1)")': (
            'self.add_param("pdlabel1", "lhapdf", hidden=True, allowed=valid_pdf, fortran_name="pdsublabel(1)")'
        ),
        'self.add_param("pdlabel2", "nn23lo1", hidden=True, allowed=valid_pdf, fortran_name="pdsublabel(2)")': (
            'self.add_param("pdlabel2", "lhapdf", hidden=True, allowed=valid_pdf, fortran_name="pdsublabel(2)")'
        ),
        'self.add_param("lhaid", 230000, hidden=True)': (
            f'self.add_param("lhaid", {LO_PDF_LHAID}, hidden=True)'
        ),
    }
    text = banner.read_text()
    updated = text
    for old, new in replacements.items():
        if old in updated:
            updated = updated.replace(old, new, 1)
        elif new not in updated:
            die(f"could not locate MG5 hidden PDF default in {banner}: {old}")
    if updated != text:
        banner.write_text(updated)


def write_herwig_input(sample: Sample, lhe_file: Path, seed: int, output: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ write Herwig input {output}")
        print(f"replace LHEFILE.lhe.gz -> {lhe_file}")
        print(f"set theGenerator:NumberOfEvents {cfg.nevents}")
        print(f"set theGenerator:RandomNumberGenerator:Seed {seed}")
        print(f"set /Herwig/Partons/thePDFset:PDFName {cfg.herwig_pdf}")
        print(f"saverun {sample.name} theGenerator")
        return

    text = cfg.template_in.read_text()
    text = text.replace("LHEFILE.lhe.gz", str(lhe_file))
    text = re.sub(r"set theGenerator:NumberOfEvents\s+\S+", f"set theGenerator:NumberOfEvents {cfg.nevents}", text)
    text = re.sub(
        r"set theGenerator:RandomNumberGenerator:Seed\s+\S+",
        f"set theGenerator:RandomNumberGenerator:Seed {seed}",
        text,
    )
    text = re.sub(
        r"set /Herwig/Partons/thePDFset:PDFName\s+\S+",
        f"set /Herwig/Partons/thePDFset:PDFName {cfg.herwig_pdf}",
        text,
    )
    text = re.sub(
        r"set /Herwig/Analysis/HwSim:OutputLocation\s+\S+",
        "set /Herwig/Analysis/HwSim:OutputLocation events/",
        text,
    )
    text = re.sub(r"saverun\s+\S+\s+theGenerator", f"saverun {sample.name} theGenerator", text)
    output.write_text(text)


def shared_library_glob(system: str) -> str:
    return "*.dylib" if system == "Darwin" else "*.so*"


def copy_library(src: Path, dest: Path) -> None:
    tmp = dest.with_name(f"{dest.name}.tmp.{os.getpid()}")
    shutil.copy2(src, tmp, follow_symlinks=True)
    tmp.replace(dest)


def prepare_collier_runtime(runtime_lib_dir: Path, cfg: Config) -> None:
    if cfg.collier_library is None:
        return

    source_lib_dir = cfg.collier_library.parent
    ensure_dir(runtime_lib_dir, cfg)
    system = platform.system()
    pattern = shared_library_glob(system)

    if cfg.dry_run:
        print(f"+ cp -pL {q(source_lib_dir / pattern)} {q(str(runtime_lib_dir) + '/')}")
        if system == "Darwin":
            print(f"+ patch OpenLoops dylib install names in {q(runtime_lib_dir)}")
        return

    for lib in sorted(source_lib_dir.glob(pattern)):
        if lib.is_file() or lib.is_symlink():
            copy_library(lib, runtime_lib_dir / lib.name)

    collier_alias = "libcollier.dylib" if system == "Darwin" else "libcollier.so"
    alias_path = runtime_lib_dir / collier_alias
    if not alias_path.exists():
        copy_library(cfg.collier_library, alias_path)

    if system == "Darwin":
        patch_openloops_dylibs(runtime_lib_dir)


def run_optional_tool(args: Sequence[object]) -> subprocess.CompletedProcess[str] | None:
    if shutil.which(str(args[0])) is None:
        return None
    return subprocess.run([str(arg) for arg in args], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)


def patch_openloops_dylibs(runtime_lib_dir: Path) -> None:
    """Make copied OpenLoops dylibs independent of the current working directory.

    The local macOS build uses install names like ``lib/libolcommon...``.  MG5
    runs helper binaries from several directories, so patch the copied dylibs to
    resolve sibling OpenLoops libraries via @loader_path.
    """

    if shutil.which("install_name_tool") is None or shutil.which("otool") is None:
        return

    dylibs = sorted(runtime_lib_dir.glob("*.dylib"))
    for dylib in dylibs:
        subprocess.run(["install_name_tool", "-id", f"@rpath/{dylib.name}", str(dylib)], stderr=subprocess.DEVNULL)

    for dylib in dylibs:
        result = run_optional_tool(["otool", "-L", dylib])
        if result is None:
            continue
        for raw_line in result.stdout.splitlines()[1:]:
            dep = raw_line.strip().split(maxsplit=1)[0]
            if not dep.startswith("lib/") or not dep.endswith(".dylib"):
                continue
            dep_name = Path(dep).name
            if (runtime_lib_dir / dep_name).exists():
                subprocess.run(
                    ["install_name_tool", "-change", dep, f"@loader_path/{dep_name}", str(dylib)],
                    stderr=subprocess.DEVNULL,
                )


def inject_mg5_runtime_rpath(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    if runtime_lib_dir is None:
        return
    make_opts = process_dir / "Source" / "make_opts"
    block = (
        "\n# gamma-gamma campaign runtime library path\n"
        f"LDFLAGS += -Wl,-rpath,{runtime_lib_dir}\n"
        f"RPATH_LIBS += -Wl,-rpath,{runtime_lib_dir}\n"
    )
    if cfg.dry_run:
        print(f"+ patch {make_opts}")
        print(block.strip())
        return
    if not make_opts.exists():
        die(f"missing MG5 make options: {make_opts}")
    text = make_opts.read_text()
    if "# gamma-gamma campaign runtime library path" not in text:
        make_opts.write_text(text.rstrip() + block)


def link_madloop_runtime_dirs(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    if runtime_lib_dir is None:
        return
    subproc_root = process_dir / "SubProcesses"
    if cfg.dry_run:
        print(f"+ link {runtime_lib_dir} as lib/ under {subproc_root}/P*")
        return
    for subproc_dir in sorted(subproc_root.glob("P*")):
        if not subproc_dir.is_dir():
            continue
        link = subproc_dir / "lib"
        if link.is_symlink():
            link.unlink()
        if not link.exists():
            link.symlink_to(runtime_lib_dir, target_is_directory=True)


def restore_mg5_symmetry_factors(process_dir: Path, cfg: Config) -> None:
    subproc_root = process_dir / "SubProcesses"
    if cfg.dry_run:
        print(f"+ restore missing symfact.dat from symfact_orig.dat under {subproc_root}/P*")
        return
    for subproc_dir in sorted(subproc_root.glob("P*")):
        symfact = subproc_dir / "symfact.dat"
        symfact_orig = subproc_dir / "symfact_orig.dat"
        if not symfact.exists() and symfact_orig.exists():
            shutil.copy2(symfact_orig, symfact)


def generation_environment(runtime_lib_dir: Path | None) -> dict[str, str] | None:
    if runtime_lib_dir is None:
        return None

    env = os.environ.copy()
    system = platform.system()
    if system == "Darwin":
        prepend_env_path(env, "DYLD_LIBRARY_PATH", runtime_lib_dir)
        prepend_env_path(env, "DYLD_FALLBACK_LIBRARY_PATH", runtime_lib_dir)
    else:
        prepend_env_path(env, "LD_LIBRARY_PATH", runtime_lib_dir)
    return env


def prepend_env_path(env: dict[str, str], key: str, path: Path) -> None:
    current = env.get(key)
    env[key] = str(path) if not current else f"{path}{os.pathsep}{current}"


def run_generate_events(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    args = [process_dir / "bin" / "generate_events", cfg.run_tag, "-f", f"--nb_core={cfg.nb_core}"]
    run(args, cfg, cwd=process_dir, env=generation_environment(runtime_lib_dir))


def run_herwig(cwd: Path, cfg: Config, args: Sequence[object]) -> None:
    run_runtime_command([cfg.herwig, *args], cfg, cwd=cwd)


def find_lhe_file(process_dir: Path, prefer_decayed: bool) -> Path:
    candidates = sorted((process_dir / "Events").glob("*/unweighted_events.lhe*"))
    if prefer_decayed:
        for candidate in candidates:
            if "decayed" in str(candidate):
                return candidate
    if candidates:
        return candidates[-1]
    die(f"could not locate MG5 LHE output in {process_dir}")


def write_root_input_list(herwig_events_dir: Path, root_input: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ find {herwig_events_dir} -type f -name '*.root' > {root_input}")
        return
    roots = sorted(herwig_events_dir.glob("**/*.root"))
    if not roots:
        die(f"no HwSim ROOT files found in {herwig_events_dir}")
    root_input.write_text("".join(f"{root}\n" for root in roots))


def run_sample(index: int, sample: Sample, cfg: Config) -> None:
    seed = cfg.seed_base + index
    sample_dir = SCRIPT_DIR / "LOAnalysis" / sample.category / "events" / sample.name
    card_dir = sample_dir / "cards"
    mg5_process_dir = sample_dir / "mg5_process"
    herwig_dir = sample_dir / "herwig"
    herwig_events_dir = herwig_dir / "events"
    root_input = sample_dir / f"{sample.name}_hwsim_roots.input"
    mg5_card = card_dir / f"{sample.name}_proc_card.dat"
    herwig_input = herwig_dir / f"{sample.name}.in"

    log(f"Running sample {sample.name}")
    print(
        f"category={sample.category} model={sample.model} process={sample.process} "
        f"weight_scale={sample.weight_scale} seed={seed}"
    )

    ensure_dir(card_dir, cfg)
    ensure_dir(herwig_events_dir, cfg)

    runtime_lib_dir: Path | None = None
    if cfg.collier_library is not None:
        runtime_lib_dir = sample_dir / "lib"
        prepare_collier_runtime(runtime_lib_dir, cfg)

    write_mg5_process_card(mg5_card, sample, mg5_process_dir, cfg)
    run(mg5_command(cfg, mg5_card), cfg)

    inject_mg5_runtime_rpath(mg5_process_dir, runtime_lib_dir, cfg)
    link_madloop_runtime_dirs(mg5_process_dir, runtime_lib_dir, cfg)
    restore_mg5_symmetry_factors(mg5_process_dir, cfg)

    patch_mg5_pdf_defaults(mg5_process_dir, cfg)
    patch_mg5_pdf_label_sync(mg5_process_dir, cfg)
    patch_run_card(mg5_process_dir / "Cards" / "run_card.dat", seed, cfg)
    generate_run_card_include(mg5_process_dir, cfg)
    patch_run_card_include(mg5_process_dir, cfg)
    if sample.madspin_decay:
        write_madspin_card(mg5_process_dir / "Cards" / "madspin_card.dat", sample.madspin_decay, cfg)

    run_generate_events(mg5_process_dir, runtime_lib_dir, cfg)

    if cfg.dry_run:
        if sample.madspin_decay:
            lhe_file = mg5_process_dir / "Events" / f"{cfg.run_tag}_decayed_1" / "unweighted_events.lhe.gz"
        else:
            lhe_file = mg5_process_dir / "Events" / cfg.run_tag / "unweighted_events.lhe.gz"
    else:
        lhe_file = find_lhe_file(mg5_process_dir, prefer_decayed=bool(sample.madspin_decay))

    write_herwig_input(sample, lhe_file, seed, herwig_input, cfg)
    run_herwig(herwig_dir, cfg, ["read", herwig_input])
    run_herwig(herwig_dir, cfg, ["run", f"{sample.name}.run", f"-N{cfg.nevents}"])

    write_root_input_list(herwig_events_dir, root_input, cfg)
    run_runtime_command([cfg.analysis_exe, root_input, "-t", cfg.run_tag, "-w", sample.weight_scale], cfg)


def main(argv: Sequence[str]) -> int:
    cfg = parse_config(argv)
    require_inputs(cfg)

    log("Building gamma-gamma post-analysis")
    run_runtime_command(["make", "-C", cfg.analysis_code_dir, "HwSimPostAnalysis_gammagamma"], cfg)

    selected = [sample for sample in SAMPLES if sample_requested(sample, cfg)]
    if not selected:
        die(f"no samples selected by RUN_SAMPLES={cfg.run_samples}")

    for index, sample in enumerate(selected):
        run_sample(index, sample, cfg)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
