#!/usr/bin/env python3
"""Run the LO h -> gamma gamma campaign.

The sample table below is intentionally plain Python.  Edit it to add, remove,
or reweight samples without having to chase shell quoting.
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_HERWIG_PREFIX = Path.home() / "Projects/Herwig/Herwig-REAL-stable-gcc-full"


@dataclass(frozen=True)
class Sample:
    name: str
    category: str
    model: str
    process: str
    madspin_decay: str
    weight_scale: float


# name | category | model | process | madspin_decay | weight_scale
SAMPLES: list[Sample] = [
    Sample("signal_gg_h_aa", "Signal", "loop_sm_haa", "g g > h [noborn=QCD]", "h > a a", 1.0),
    Sample("bkg_prompt_aa", "Backgrounds", "sm", "p p > a a", "", 1.0),
    # Loop-induced prompt continuum.  This is separate from the tree-level
    # q qbar -> gamma gamma component generated by "p p > a a" in the SM.
    # Sample("bkg_loop_gg_aa", "Backgrounds", "loop_sm", "g g > a a [noborn=QCD]", "", 1.0),
    # Reducible fake-background starting points.  Set the weight scale to the
    # desired total fake cross-section factor before enabling them.
    # Sample("bkg_gamma_j", "Backgrounds", "sm", "p p > a j", "", 1.0),
    # Sample("bkg_jj", "Backgrounds", "sm", "p p > j j", "", 1.0),
    # Sample("bkg_ee", "Backgrounds", "sm", "p p > e+ e-", "", 1.0),
]


@dataclass
class Config:
    nevents: int
    ebeam: float
    mg5_dir: Path
    herwig: str
    herwig_env: Path | None
    herwig_pdf: str
    collier_library: Path | None
    run_tag: str
    run_samples: str
    dry_run: bool
    nb_core: int
    seed_base: int
    gen_photon_pt_min: float
    gen_photon_eta_max: float
    gen_jet_pt_min: float
    gen_jet_eta_max: float
    gen_lepton_pt_min: float
    gen_lepton_eta_max: float
    gen_draa_min: float
    gen_draj_min: float
    gen_dral_min: float
    gen_drjj_min: float
    gen_drll_min: float

    @property
    def template_in(self) -> Path:
        return SCRIPT_DIR / "HW-template.in"

    @property
    def analysis_code_dir(self) -> Path:
        return SCRIPT_DIR / "LOAnalysis" / "Code"

    @property
    def analysis_exe(self) -> Path:
        return self.analysis_code_dir / "HwSimPostAnalysis_gammagamma"


def env_text(name: str, default: str) -> str:
    return os.environ.get(name, default)


def env_int(name: str, default: int) -> int:
    return int(os.environ.get(name, str(default)))


def env_float(name: str, default: float) -> float:
    return float(os.environ.get(name, str(default)))


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def maybe_path(value: str | None) -> Path | None:
    if not value:
        return None
    return Path(value).expanduser()


def guess_herwig_env() -> Path | None:
    explicit = maybe_path(os.environ.get("HERWIG_ENV"))
    if explicit:
        return explicit
    default = maybe_path(os.environ.get("DEFAULT_HERWIG_ENV"))
    if default and default.exists():
        return default
    candidate = DEFAULT_HERWIG_PREFIX / "bin" / "activate"
    return candidate if candidate.exists() else None


def guess_collier_library(herwig_env: Path | None) -> Path | None:
    explicit = os.environ.get("COLLIER_LIBRARY") or os.environ.get("COLLIER_DYLIB")
    if explicit:
        return Path(explicit).expanduser()

    prefix = DEFAULT_HERWIG_PREFIX
    if herwig_env and herwig_env.name == "activate":
        prefix = herwig_env.parent.parent

    system = platform.system()
    if system == "Darwin":
        fixed_candidates = [
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.2.dylib",
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.dylib",
        ]
        glob_pattern = "libcollier*.dylib"
    else:
        fixed_candidates = [
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.so",
            prefix / "opt" / "OpenLoops-2.1.4" / "lib" / "libcollier.so.2",
        ]
        glob_pattern = "libcollier.so*"

    for candidate in fixed_candidates:
        if candidate.exists():
            return candidate

    opt_dir = prefix / "opt"
    if opt_dir.exists():
        for candidate in sorted(opt_dir.glob(f"OpenLoops-*/lib/{glob_pattern}")):
            if candidate.exists():
                return candidate
    return None


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nevents", type=int, default=env_int("NEVENTS", 10000))
    parser.add_argument("--ebeam", type=float, default=env_float("EBEAM", 20000.0))
    parser.add_argument("--mg5-dir", type=Path, default=Path(env_text("MG5_DIR", str(REPO_ROOT / "MG5_aMC_v3_5_15"))))
    parser.add_argument("--herwig", default=env_text("HERWIG", "Herwig"))
    parser.add_argument("--herwig-env", type=Path, default=guess_herwig_env())
    parser.add_argument("--herwig-pdf", default=env_text("HERWIG_PDF", "NNPDF31_nnlo_as_0118"))
    parser.add_argument("--collier-library", type=Path, default=None)
    parser.add_argument("--run-tag", default=env_text("RUN_TAG", "run_01"))
    parser.add_argument("--run-samples", default=env_text("RUN_SAMPLES", "signal_gg_h_aa,bkg_prompt_aa"))
    parser.add_argument("--dry-run", action="store_true", default=env_bool("DRY_RUN", False))
    parser.add_argument("--nb-core", type=int, default=env_int("NB_CORE", 1))
    parser.add_argument("--seed-base", type=int, default=env_int("SEED_BASE", 31122002))
    parser.add_argument("--gen-photon-pt-min", type=float, default=env_float("GEN_PHOTON_PT_MIN", 10.0))
    parser.add_argument("--gen-photon-eta-max", type=float, default=env_float("GEN_PHOTON_ETA_MAX", 6.0))
    parser.add_argument("--gen-jet-pt-min", type=float, default=env_float("GEN_JET_PT_MIN", 10.0))
    parser.add_argument("--gen-jet-eta-max", type=float, default=env_float("GEN_JET_ETA_MAX", 6.0))
    parser.add_argument("--gen-lepton-pt-min", type=float, default=env_float("GEN_LEPTON_PT_MIN", 10.0))
    parser.add_argument("--gen-lepton-eta-max", type=float, default=env_float("GEN_LEPTON_ETA_MAX", 6.0))
    parser.add_argument("--gen-draa-min", type=float, default=env_float("GEN_DRAA_MIN", 0.4))
    parser.add_argument("--gen-draj-min", type=float, default=env_float("GEN_DRAJ_MIN", 0.4))
    parser.add_argument("--gen-dral-min", type=float, default=env_float("GEN_DRAL_MIN", 0.4))
    parser.add_argument("--gen-drjj-min", type=float, default=env_float("GEN_DRJJ_MIN", 0.4))
    parser.add_argument("--gen-drll-min", type=float, default=env_float("GEN_DRLL_MIN", 0.0))
    return parser


def parse_config(argv: Sequence[str]) -> Config:
    args = build_parser().parse_args(argv)
    collier_library = args.collier_library or guess_collier_library(args.herwig_env)
    return Config(
        nevents=args.nevents,
        ebeam=args.ebeam,
        mg5_dir=args.mg5_dir.expanduser(),
        herwig=args.herwig,
        herwig_env=args.herwig_env.expanduser() if args.herwig_env else None,
        herwig_pdf=args.herwig_pdf,
        collier_library=collier_library.expanduser() if collier_library else None,
        run_tag=args.run_tag,
        run_samples=args.run_samples,
        dry_run=args.dry_run,
        nb_core=args.nb_core,
        seed_base=args.seed_base,
        gen_photon_pt_min=args.gen_photon_pt_min,
        gen_photon_eta_max=args.gen_photon_eta_max,
        gen_jet_pt_min=args.gen_jet_pt_min,
        gen_jet_eta_max=args.gen_jet_eta_max,
        gen_lepton_pt_min=args.gen_lepton_pt_min,
        gen_lepton_eta_max=args.gen_lepton_eta_max,
        gen_draa_min=args.gen_draa_min,
        gen_draj_min=args.gen_draj_min,
        gen_dral_min=args.gen_dral_min,
        gen_drjj_min=args.gen_drjj_min,
        gen_drll_min=args.gen_drll_min,
    )


def q(value: object) -> str:
    return shlex.quote(str(value))


def format_command(args: Sequence[object]) -> str:
    return " ".join(q(arg) for arg in args)


def log(message: str) -> None:
    print(f"\n==> {message}")


def die(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def ensure_dir(path: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ mkdir -p {q(path)}")
    else:
        path.mkdir(parents=True, exist_ok=True)


def run(args: Sequence[object], cfg: Config, cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    prefix = f"+ cd {q(cwd)} && " if cwd else "+ "
    print(prefix + format_command(args))
    if cfg.dry_run:
        return
    subprocess.run([str(arg) for arg in args], cwd=cwd, env=env, check=True)


def run_shell(command: str, cfg: Config, cwd: Path | None = None, env: dict[str, str] | None = None) -> None:
    run(["bash", "-lc", command], cfg, cwd=cwd, env=env)


def require_inputs(cfg: Config) -> None:
    if not cfg.template_in.exists():
        die(f"missing Herwig template: {cfg.template_in}")
    if not (cfg.mg5_dir / "bin" / "mg5_aMC").exists():
        die(f"missing MG5 executable: {cfg.mg5_dir / 'bin' / 'mg5_aMC'}")
    if cfg.herwig_env and not cfg.herwig_env.exists():
        die(f"missing Herwig activation script: {cfg.herwig_env}")
    if cfg.collier_library and not cfg.collier_library.exists():
        die(f"missing COLLIER/OpenLoops library: {cfg.collier_library}")


def sample_requested(sample: Sample, cfg: Config) -> bool:
    if cfg.run_samples == "all":
        return True
    requested = {part.strip() for part in cfg.run_samples.split(",") if part.strip()}
    return sample.name in requested


def write_mg5_process_card(card: Path, sample: Sample, output_dir: Path, cfg: Config) -> None:
    text = f"""import model {sample.model}
define p = g u c d s u~ c~ d~ s~
define j = g u c d s u~ c~ d~ s~
define l+ = e+ mu+
define l- = e- mu-
define vl = ve vm vt
define vl~ = ve~ vm~ vt~
generate {sample.process}
output {output_dir} -f
"""
    if cfg.dry_run:
        print(f"+ write MG5 process card {card}")
        print(text, end="")
    else:
        card.write_text(text)


def write_madspin_card(card: Path, decay: str, cfg: Config) -> None:
    text = f"""set spinmode none
decay {decay}
launch
"""
    if cfg.dry_run:
        print(f"+ write MadSpin card {card}")
        print(text, end="")
    else:
        card.write_text(text)


def patch_run_card(card: Path, seed: int, cfg: Config) -> None:
    updates = {
        "nevents": str(cfg.nevents),
        "ebeam1": str(cfg.ebeam),
        "ebeam2": str(cfg.ebeam),
        "iseed": str(seed),
        "pta": str(cfg.gen_photon_pt_min),
        "etaa": str(cfg.gen_photon_eta_max),
        "ptj": str(cfg.gen_jet_pt_min),
        "etaj": str(cfg.gen_jet_eta_max),
        "ptl": str(cfg.gen_lepton_pt_min),
        "etal": str(cfg.gen_lepton_eta_max),
        "draa": str(cfg.gen_draa_min),
        "draj": str(cfg.gen_draj_min),
        "dral": str(cfg.gen_dral_min),
        "drjj": str(cfg.gen_drjj_min),
        "drll": str(cfg.gen_drll_min),
    }
    if cfg.dry_run:
        print(f"+ patch run card {card}")
        print(
            "nevents={nevents}, ebeam1={ebeam1}, ebeam2={ebeam2}, iseed={iseed}".format(**updates)
        )
        print(
            "pta={pta}, etaa={etaa}, ptj={ptj}, etaj={etaj}, "
            "ptl={ptl}, etal={etal}, draa={draa}, draj={draj}, dral={dral}, "
            "drjj={drjj}, drll={drll}".format(**updates)
        )
        return

    pattern = re.compile(r"^(\s*)([^=]+?)(\s*=\s*)([A-Za-z0-9_]+)(.*)$")
    output_lines: list[str] = []
    for line in card.read_text().splitlines(keepends=True):
        match = pattern.match(line)
        if match:
            indent, _value, sep, key, tail = match.groups()
            if key in updates:
                line = f"{indent}{updates[key]:>12}{sep}{key}{tail}\n"
        output_lines.append(line)
    card.write_text("".join(output_lines))


def write_herwig_input(sample: Sample, lhe_file: Path, seed: int, output: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ write Herwig input {output}")
        print(f"replace LHEFILE.lhe.gz -> {lhe_file}")
        print(f"set theGenerator:NumberOfEvents {cfg.nevents}")
        print(f"set theGenerator:RandomNumberGenerator:Seed {seed}")
        print(f"set /Herwig/Partons/thePDFset:PDFName {cfg.herwig_pdf}")
        print(f"saverun {sample.name} theGenerator")
        return

    text = cfg.template_in.read_text()
    text = text.replace("LHEFILE.lhe.gz", str(lhe_file))
    text = re.sub(r"set theGenerator:NumberOfEvents\s+\S+", f"set theGenerator:NumberOfEvents {cfg.nevents}", text)
    text = re.sub(
        r"set theGenerator:RandomNumberGenerator:Seed\s+\S+",
        f"set theGenerator:RandomNumberGenerator:Seed {seed}",
        text,
    )
    text = re.sub(
        r"set /Herwig/Partons/thePDFset:PDFName\s+\S+",
        f"set /Herwig/Partons/thePDFset:PDFName {cfg.herwig_pdf}",
        text,
    )
    text = re.sub(
        r"set /Herwig/Analysis/HwSim:OutputLocation\s+\S+",
        "set /Herwig/Analysis/HwSim:OutputLocation events/",
        text,
    )
    text = re.sub(r"saverun\s+\S+\s+theGenerator", f"saverun {sample.name} theGenerator", text)
    output.write_text(text)


def shared_library_glob(system: str) -> str:
    return "*.dylib" if system == "Darwin" else "*.so*"


def copy_library(src: Path, dest: Path) -> None:
    tmp = dest.with_name(f"{dest.name}.tmp.{os.getpid()}")
    shutil.copy2(src, tmp, follow_symlinks=True)
    tmp.replace(dest)


def prepare_collier_runtime(runtime_lib_dir: Path, cfg: Config) -> None:
    if cfg.collier_library is None:
        return

    source_lib_dir = cfg.collier_library.parent
    ensure_dir(runtime_lib_dir, cfg)
    system = platform.system()
    pattern = shared_library_glob(system)

    if cfg.dry_run:
        print(f"+ cp -pL {q(source_lib_dir / pattern)} {q(str(runtime_lib_dir) + '/')}")
        if system == "Darwin":
            print(f"+ patch OpenLoops dylib install names in {q(runtime_lib_dir)}")
        return

    for lib in sorted(source_lib_dir.glob(pattern)):
        if lib.is_file() or lib.is_symlink():
            copy_library(lib, runtime_lib_dir / lib.name)

    collier_alias = "libcollier.dylib" if system == "Darwin" else "libcollier.so"
    alias_path = runtime_lib_dir / collier_alias
    if not alias_path.exists():
        copy_library(cfg.collier_library, alias_path)

    if system == "Darwin":
        patch_openloops_dylibs(runtime_lib_dir)


def run_optional_tool(args: Sequence[object]) -> subprocess.CompletedProcess[str] | None:
    if shutil.which(str(args[0])) is None:
        return None
    return subprocess.run([str(arg) for arg in args], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)


def patch_openloops_dylibs(runtime_lib_dir: Path) -> None:
    """Make copied OpenLoops dylibs independent of the current working directory.

    The local macOS build uses install names like ``lib/libolcommon...``.  MG5
    runs helper binaries from several directories, so patch the copied dylibs to
    resolve sibling OpenLoops libraries via @loader_path.
    """

    if shutil.which("install_name_tool") is None or shutil.which("otool") is None:
        return

    dylibs = sorted(runtime_lib_dir.glob("*.dylib"))
    for dylib in dylibs:
        subprocess.run(["install_name_tool", "-id", f"@rpath/{dylib.name}", str(dylib)], stderr=subprocess.DEVNULL)

    for dylib in dylibs:
        result = run_optional_tool(["otool", "-L", dylib])
        if result is None:
            continue
        for raw_line in result.stdout.splitlines()[1:]:
            dep = raw_line.strip().split(maxsplit=1)[0]
            if not dep.startswith("lib/") or not dep.endswith(".dylib"):
                continue
            dep_name = Path(dep).name
            if (runtime_lib_dir / dep_name).exists():
                subprocess.run(
                    ["install_name_tool", "-change", dep, f"@loader_path/{dep_name}", str(dylib)],
                    stderr=subprocess.DEVNULL,
                )


def inject_mg5_runtime_rpath(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    if runtime_lib_dir is None:
        return
    make_opts = process_dir / "Source" / "make_opts"
    block = (
        "\n# gamma-gamma campaign runtime library path\n"
        f"LDFLAGS += -Wl,-rpath,{runtime_lib_dir}\n"
        f"RPATH_LIBS += -Wl,-rpath,{runtime_lib_dir}\n"
    )
    if cfg.dry_run:
        print(f"+ patch {make_opts}")
        print(block.strip())
        return
    if not make_opts.exists():
        die(f"missing MG5 make options: {make_opts}")
    text = make_opts.read_text()
    if "# gamma-gamma campaign runtime library path" not in text:
        make_opts.write_text(text.rstrip() + block)


def link_madloop_runtime_dirs(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    if runtime_lib_dir is None:
        return
    subproc_root = process_dir / "SubProcesses"
    if cfg.dry_run:
        print(f"+ link {runtime_lib_dir} as lib/ under {subproc_root}/P*")
        return
    for subproc_dir in sorted(subproc_root.glob("P*")):
        if not subproc_dir.is_dir():
            continue
        link = subproc_dir / "lib"
        if link.is_symlink():
            link.unlink()
        if not link.exists():
            link.symlink_to(runtime_lib_dir, target_is_directory=True)


def restore_mg5_symmetry_factors(process_dir: Path, cfg: Config) -> None:
    subproc_root = process_dir / "SubProcesses"
    if cfg.dry_run:
        print(f"+ restore missing symfact.dat from symfact_orig.dat under {subproc_root}/P*")
        return
    for subproc_dir in sorted(subproc_root.glob("P*")):
        symfact = subproc_dir / "symfact.dat"
        symfact_orig = subproc_dir / "symfact_orig.dat"
        if not symfact.exists() and symfact_orig.exists():
            shutil.copy2(symfact_orig, symfact)


def generation_environment(runtime_lib_dir: Path | None) -> dict[str, str] | None:
    if runtime_lib_dir is None:
        return None

    env = os.environ.copy()
    system = platform.system()
    if system == "Darwin":
        prepend_env_path(env, "DYLD_LIBRARY_PATH", runtime_lib_dir)
        prepend_env_path(env, "DYLD_FALLBACK_LIBRARY_PATH", runtime_lib_dir)
    else:
        prepend_env_path(env, "LD_LIBRARY_PATH", runtime_lib_dir)
    return env


def prepend_env_path(env: dict[str, str], key: str, path: Path) -> None:
    current = env.get(key)
    env[key] = str(path) if not current else f"{path}{os.pathsep}{current}"


def run_generate_events(process_dir: Path, runtime_lib_dir: Path | None, cfg: Config) -> None:
    args = [process_dir / "bin" / "generate_events", cfg.run_tag, "-f", f"--nb_core={cfg.nb_core}"]
    run(args, cfg, cwd=process_dir, env=generation_environment(runtime_lib_dir))


def run_herwig(cwd: Path, cfg: Config, args: Sequence[object]) -> None:
    if cfg.herwig_env:
        quoted_args = " ".join(q(arg) for arg in args)
        command = f"source {q(cfg.herwig_env)}; {q(cfg.herwig)} {quoted_args}"
        run_shell(command, cfg, cwd=cwd)
    else:
        run([cfg.herwig, *args], cfg, cwd=cwd)


def find_lhe_file(process_dir: Path, prefer_decayed: bool) -> Path:
    candidates = sorted((process_dir / "Events").glob("*/unweighted_events.lhe*"))
    if prefer_decayed:
        for candidate in candidates:
            if "decayed" in str(candidate):
                return candidate
    if candidates:
        return candidates[-1]
    die(f"could not locate MG5 LHE output in {process_dir}")


def write_root_input_list(herwig_events_dir: Path, root_input: Path, cfg: Config) -> None:
    if cfg.dry_run:
        print(f"+ find {herwig_events_dir} -type f -name '*.root' > {root_input}")
        return
    roots = sorted(herwig_events_dir.glob("**/*.root"))
    if not roots:
        die(f"no HwSim ROOT files found in {herwig_events_dir}")
    root_input.write_text("".join(f"{root}\n" for root in roots))


def run_sample(index: int, sample: Sample, cfg: Config) -> None:
    seed = cfg.seed_base + index
    sample_dir = SCRIPT_DIR / "LOAnalysis" / sample.category / "events" / sample.name
    card_dir = sample_dir / "cards"
    mg5_process_dir = sample_dir / "mg5_process"
    herwig_dir = sample_dir / "herwig"
    herwig_events_dir = herwig_dir / "events"
    root_input = sample_dir / f"{sample.name}_hwsim_roots.input"
    mg5_card = card_dir / f"{sample.name}_proc_card.dat"
    herwig_input = herwig_dir / f"{sample.name}.in"

    log(f"Running sample {sample.name}")
    print(
        f"category={sample.category} model={sample.model} process={sample.process} "
        f"weight_scale={sample.weight_scale} seed={seed}"
    )

    ensure_dir(card_dir, cfg)
    ensure_dir(herwig_events_dir, cfg)

    runtime_lib_dir: Path | None = None
    if cfg.collier_library is not None:
        runtime_lib_dir = sample_dir / "lib"
        prepare_collier_runtime(runtime_lib_dir, cfg)

    write_mg5_process_card(mg5_card, sample, mg5_process_dir, cfg)
    run([cfg.mg5_dir / "bin" / "mg5_aMC", mg5_card], cfg)

    inject_mg5_runtime_rpath(mg5_process_dir, runtime_lib_dir, cfg)
    link_madloop_runtime_dirs(mg5_process_dir, runtime_lib_dir, cfg)
    restore_mg5_symmetry_factors(mg5_process_dir, cfg)

    patch_run_card(mg5_process_dir / "Cards" / "run_card.dat", seed, cfg)
    if sample.madspin_decay:
        write_madspin_card(mg5_process_dir / "Cards" / "madspin_card.dat", sample.madspin_decay, cfg)

    run_generate_events(mg5_process_dir, runtime_lib_dir, cfg)

    if cfg.dry_run:
        if sample.madspin_decay:
            lhe_file = mg5_process_dir / "Events" / f"{cfg.run_tag}_decayed_1" / "unweighted_events.lhe.gz"
        else:
            lhe_file = mg5_process_dir / "Events" / cfg.run_tag / "unweighted_events.lhe.gz"
    else:
        lhe_file = find_lhe_file(mg5_process_dir, prefer_decayed=bool(sample.madspin_decay))

    write_herwig_input(sample, lhe_file, seed, herwig_input, cfg)
    run_herwig(herwig_dir, cfg, ["read", herwig_input])
    run_herwig(herwig_dir, cfg, ["run", f"{sample.name}.run", f"-N{cfg.nevents}"])

    write_root_input_list(herwig_events_dir, root_input, cfg)
    run([cfg.analysis_exe, root_input, "-t", cfg.run_tag, "-w", sample.weight_scale], cfg)


def main(argv: Sequence[str]) -> int:
    cfg = parse_config(argv)
    require_inputs(cfg)

    log("Building gamma-gamma post-analysis")
    run(["make", "-C", cfg.analysis_code_dir, "HwSimPostAnalysis_gammagamma"], cfg)

    selected = [sample for sample in SAMPLES if sample_requested(sample, cfg)]
    if not selected:
        die(f"no samples selected by RUN_SAMPLES={cfg.run_samples}")

    for index, sample in enumerate(selected):
        run_sample(index, sample, cfg)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
